/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.30
 * Generated at: 2013-01-30 00:44:14 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.jsp.backlog;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.io.*;
import java.util.*;
import java.text.*;
import mantenedores.MBackLogSelect;
import persistencia.HelperHSQL;
import dto.DTOBackLog;

public final class IngresoPosIt_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

String Fecha = new SimpleDateFormat("yyyy-MM-dd").format(new Date());
String Hora  = new SimpleDateFormat("HH:mm:ss").format(new Date());

String Flag = "";

int id = 0;
String[] list = {"#deac2f", "7FFF00 ", "#fff000", "#56c4e8", "#e9e74a"}; //FF8C00 

Random r = new Random();
String color = "";
	   color = list[r.nextInt(list.length)];


if (request.getParameter("flag") != null) {
	Flag = "1";
	//Recoger parametros submited
	String Actividad = request.getParameter("tipo");
	String Detalle1 = request.getParameter("det1");
	String Detalle2 = request.getParameter("det2");
	String Detalle3 = "0";
	String FechaBL = request.getParameter("fecha");
	//Grabar Registro
	/* -------------------------------  */
	MBackLogSelect backlog   = new MBackLogSelect();
	id = backlog.identidad();
	int Ret = backlog.GrabaBackLog(id, Actividad, Detalle1, Detalle2, color, FechaBL);   //(Actividad, Detalle1, Detalle2, Detalle3, FechaBL);
	/* -------------------------------  */
}


      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("<link type=\"text/css\" rel=\"stylesheet\" media=\"all\" href=\"../../css/formulario.css\">\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" media=\"all\" href=\"../../css/jsDatePick_ltr.min.css\" />\r\n");
      out.write("<script type=\"text/javascript\" src=\"../../js/jsDatePick.min.1.3.js\"></script>\r\n");
      out.write("<title>KANBAN::BACKLOG</title>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("window.onload = function(){\r\n");
      out.write("\tnew JsDatePick({\r\n");
      out.write("\t\tuseMode:2,\r\n");
      out.write("\t\ttarget:\"fecha\",\r\n");
      out.write("\t\tdateFormat:\"%d-%m-%Y\"\r\n");
      out.write("\t});\r\n");
      out.write("};\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<div height=1>&nbsp;</div>\r\n");
      out.write("\t<div align=center>\r\n");
      out.write("\t\t<table width=1024 align=center border=0 cellspacing=1 celpadding=1>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td align=left>\r\n");
      out.write("\t\t\t\t\t<img src=\"../../images/BrandingKanbanL.png\"> \r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t</table>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!-- <form id='upData' name='upData' action='MuestraPosIt.jsp' method='post'>  -->   \r\n");
      out.write("\t<form id='upData' name='upData' action=# method='post'>        \r\n");
      out.write("\t\t<div class=\"box\">            \r\n");
      out.write("\t\t\t <h1>Datos&nbsp;&nbsp;BackLog: ");
      out.print(Fecha);
      out.write("</h1>             \r\n");
      out.write("\t\t\t <table border=0>\r\n");
      out.write("\t\t\t \t<tr>\r\n");
      out.write("\t\t\t \t   <td width=35%>\r\n");
      out.write("\t\t\t\t \t   \t<label>                \r\n");
      out.write("\t\t\t\t\t\t\t <span>Actividad : </span><input type=\"text\" class=\"input_text\" name=\"tipo\" id=\"tipo\" maxlenght=19 >\r\n");
      out.write("\t\t\t\t\t  \t </label>\r\n");
      out.write("\t\t\t \t   </td>\r\n");
      out.write("\t\t\t \t   <td>\r\n");
      out.write("\t\t\t \t   \t\t<label>\r\n");
      out.write("\t\t\t\t\t\t\t <span>Detalle 1 : </span><input type=\"text\" class=\"input_text\" name=\"det1\" id=\"det1\"/>  \r\n");
      out.write("\t\t\t\t\t\t</label>\r\n");
      out.write("\t\t\t \t   </td>\r\n");
      out.write("\t\t\t \t   <td>\r\n");
      out.write("\t\t\t\t \t\t <label>\r\n");
      out.write("\t\t\t\t\t\t\t <span>Detalle 2 : </span><input type=\"text\" class=\"input_text\" name=\"det2\" id=\"det2\"/>            \r\n");
      out.write("\t\t\t\t\t\t</label>\r\n");
      out.write("\t\t\t \t   </td>\r\n");
      out.write("\t\t\t \t</tr>\r\n");
      out.write("\t\t\t \t<tr>\r\n");
      out.write("\t\t\t \t   <td colspan=2>\r\n");
      out.write("\t\t\t\t \t   \t<label>                \r\n");
      out.write("\t\t\t\t\t\t\t<span>&nbsp;&nbsp;&nbsp;Fecha : </span>\r\n");
      out.write("\t\t\t\t\t\t\t <input type=\"text\" class=\"input_text\" size=\"12\" id=\"fecha\" name=\"fecha\"/>  \t \r\n");
      out.write("\t\t\t\t\t\t </label>\r\n");
      out.write("\t\t\t \t   </td>\r\n");
      out.write("\r\n");
      out.write("\t\t\t \t   <td width=34%>\r\n");
      out.write("\t\t\t\t \t\t <label>\r\n");
      out.write("\t\t\t\t\t\t\t <input type=\"submit\" class=\"button\" value=\"Graba Pos-it\" />             \r\n");
      out.write("\t\t\t\t\t\t</label>\r\n");
      out.write("\t\t\t \t   </td>\r\n");
      out.write("\t\t\t \t</tr>\r\n");
      out.write("\t\t\t</table>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<!-- /* ---------------------------- CUERPO --------------------------- */ -->\r\n");
      out.write("\t\t<div hight=30>&nbsp;</div>\r\n");
      out.write("\t\t<!-- /* ---------------------------- CUERPO --------------------------- */ -->\r\n");
      out.write("\t \t");
if (Flag != ""){
      out.write("\r\n");
      out.write("\t \t<div class=\"box\">            \r\n");
      out.write("\t\t\t<h1>Pos-It&nbsp;&nbsp;BackLog:</h1>   \r\n");
      out.write("\t\t\t");

			/* -------------------------------  */
			/* MBackLogSelect backlog   = new MBackLogSelect();
				     ArrayList backlogs = backlog.ListaBackLogs(); */
			/* -------------------------------  */
			HelperHSQL backlog = new HelperHSQL();
			ArrayList backlogs = backlog.HelperListaBackLogs();
			/* -------------------------------  */
			Iterator itBL = backlogs.iterator();
      out.write("\r\n");
      out.write("\t\t\t<div align=center>\r\n");
      out.write("\t\t\t<div id=tableContainer class=tableContainer>\r\n");
      out.write("\t\t\t\t<table border=0 cellspacing=0 cellpadding=0 width=1020px;>\r\n");
      out.write("\t\t\t\t");

				    
					while (itBL.hasNext()){
						DTOBackLog obBL = (DTOBackLog) itBL.next();
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<tr bgcolor=#262626>\r\n");
      out.write("\t\t\t\t\t\t\t<td align=left width=24%>\r\n");
      out.write("\t\t\t\t\t\t\t\t<label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<font face=Tahoma size=2 color=#deac2f><b>");
      out.print(obBL.getID());
      out.write(':');
      out.write(' ');
      out.write(':');
      out.print(obBL.getActividad() );
      out.write("</b></font>\r\n");
      out.write("\t\t\t\t\t\t\t\t</label> \r\n");
      out.write("\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td align=left width=24%> \r\n");
      out.write("\t\t\t\t\t\t\t\t<label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<font face=Tahoma size=2 color=#ffff00>");
      out.print(obBL.getDetalle1());
      out.write("</font>\r\n");
      out.write("\t\t\t\t\t\t\t\t</label>\r\n");
      out.write("\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td align=left width=24%>\r\n");
      out.write("\t\t\t\t\t\t\t\t<label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<font face=Tahoma size=2 color=#ffff00>");
      out.print(obBL.getDetalle2());
      out.write("</font>\r\n");
      out.write("\t\t\t\t\t\t\t\t</label>\r\n");
      out.write("\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td align=left width=24%>\r\n");
      out.write("\t\t\t\t\t\t\t\t<label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<font face=Tahoma size=2 color=#ff0000>");
      out.print(obBL.getFecha());
      out.write("</font>\r\n");
      out.write("\t\t\t\t\t\t\t\t</label>\r\n");
      out.write("\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td width=4% bgcolor='");
      out.print(obBL.getDetalle3());
      out.write("'>\r\n");
      out.write("\t\t\t\t\t\t\t\t<label><span>");
      out.print(obBL.getDetalle3());
      out.write("</span></label>\r\n");
      out.write("\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t");
}
      out.write("\r\n");
      out.write("\t\t\t\t\t");
      out.write("\r\n");
      out.write("\t\t\t\t</table>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div> \r\n");
      out.write("\t\t");
} else {
      out.write("\r\n");
      out.write("\t\t<div class=\"box\">            \r\n");
      out.write("\t\t\t<h1>Pos-It&nbsp;&nbsp;BackLog: ");
      out.print(Fecha);
      out.write("</h1>  \r\n");
      out.write("\t\t\t");

			/* -------------------------------  */
			MBackLogSelect backlog   = new MBackLogSelect();
			ArrayList backlogs = backlog.ListaBackLogs();
			/* -------------------------------  */
			Iterator itBL = backlogs.iterator();
      out.write("\r\n");
      out.write("\t\t\t<div align=center>\r\n");
      out.write("\t\t\t<div id=tableContainer class=tableContainer>\r\n");
      out.write("\t\t\t\t<table border=0 cellspacing=0 cellpadding=0 width=1020px;>\r\n");
      out.write("\t\t\t\t");

				    
					while (itBL.hasNext()){
						DTOBackLog obBL = (DTOBackLog) itBL.next();
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<tr bgcolor=#262626>\r\n");
      out.write("\t\t\t\t\t\t\t<td align=left width=24%>\r\n");
      out.write("\t\t\t\t\t\t\t\t<label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<font face=Tahoma size=2 color=#deac2f><b>");
      out.print(obBL.getID());
      out.write(':');
      out.write(' ');
      out.write(':');
      out.print(obBL.getActividad() );
      out.write("</b></font>\r\n");
      out.write("\t\t\t\t\t\t\t\t</label> \r\n");
      out.write("\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td align=left width=24%> \r\n");
      out.write("\t\t\t\t\t\t\t\t<label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<font face=Tahoma size=2 color=#ffff00>");
      out.print(obBL.getDetalle1());
      out.write("</font>\r\n");
      out.write("\t\t\t\t\t\t\t\t</label>\r\n");
      out.write("\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td align=left width=24%>\r\n");
      out.write("\t\t\t\t\t\t\t\t<label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<font face=Tahoma size=2 color=#ffff00>");
      out.print(obBL.getDetalle2());
      out.write("</font>\r\n");
      out.write("\t\t\t\t\t\t\t\t</label>\r\n");
      out.write("\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td align=left width=24%>\r\n");
      out.write("\t\t\t\t\t\t\t\t<label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<font face=Tahoma size=2 color=#ff0000>");
      out.print(obBL.getFecha());
      out.write("</font>\r\n");
      out.write("\t\t\t\t\t\t\t\t</label>\r\n");
      out.write("\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td width=4% bgcolor='");
      out.print(obBL.getDetalle3());
      out.write("'>\r\n");
      out.write("\t\t\t\t\t\t\t\t<label><span>");
      out.print(obBL.getDetalle3());
      out.write("</span></label>\r\n");
      out.write("\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t");
}
      out.write("\r\n");
      out.write("\t\t\t\t\t");
      out.write("\r\n");
      out.write("\t\t\t\t</table>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t ");
}
      out.write("\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t\t                                   \r\n");
      out.write("\t <input type=\"hidden\" name=\"flag\" id=\"flag\" value='");
      out.print(Flag);
      out.write("' /> \r\n");
      out.write("\t \t       \r\n");
      out.write("\t </form>\r\n");
      out.write("\t\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
